import type { DatabaseClient } from './client';
import { asCount, asText } from './rows';

export type JobType = 'EVIDENCE_PROCESSING' | 'AUDIO_TRANSCRIPTION' | 'AUDIT_RUN';
export type JobStatus = 'QUEUED' | 'RUNNING' | 'SUCCEEDED' | 'FAILED';
const JOB_COLUMNS = 'id,audit_id,job_type,operation_scope,idempotency_key,input_fingerprint,payload,evidence_id,status,progress,attempt_count,max_attempts,last_error_code,last_error_message_sanitized,available_at,created_at,started_at,finished_at,timeout_at';
const ARTIFACT_COLUMNS = 'id,job_id,evidence_id,artifact_type,result,content_sha256,extractor_version,provider,created_at';

interface JobRow { id: string; audit_id?: string | null; job_type: JobType; operation_scope: string; idempotency_key: string; input_fingerprint: string; payload: unknown; evidence_id?: string | null; status: JobStatus; progress?: number | null; attempt_count?: number | null; max_attempts?: number | null; last_error_code?: string | null; last_error_message_sanitized?: string | null; available_at: string; created_at: string; started_at?: string | null; finished_at?: string | null; timeout_at?: string | null; }
interface ClaimRow { job_id: string; attempt_number: number; audit_id?: string | null; job_type: JobType; payload: unknown; evidence_id?: string | null; attempt_count?: number | null; max_attempts?: number | null; timeout_at?: string | null; }
interface ArtifactRow { id: string; job_id: string; evidence_id?: string | null; artifact_type: string; result: unknown; content_sha256?: string | null; extractor_version?: string | null; provider?: string | null; created_at: string; }

export interface EnqueueJobInput { auditId: string; jobType: JobType; operationScope: string; idempotencyKey: string; inputFingerprint: string; payload?: unknown; evidenceId?: string | null; maxAttempts?: number; actorId?: string | null; }
export interface JobRecord { id: string; auditId: string | null; jobType: JobType; operationScope: string; idempotencyKey: string; inputFingerprint: string; payload: unknown; evidenceId: string | null; status: JobStatus; progress: number; attemptCount: number; maxAttempts: number; lastErrorCode: string | null; lastErrorMessageSanitized: string | null; availableAt: string; createdAt: string; startedAt: string | null; finishedAt: string | null; timeoutAt: string | null; }
export interface ClaimedJob { jobId: string; attemptNumber: number; auditId: string | null; jobType: JobType; payload: unknown; evidenceId: string | null; attemptCount: number; maxAttempts: number; timeoutAt: string | null; }
export interface JobArtifactRecord { id: string; jobId: string; evidenceId: string | null; artifactType: string; result: unknown; contentSha256: string | null; extractorVersion: string | null; provider: string | null; createdAt: string; }

function toJob(row: JobRow): JobRecord { return { id: row.id, auditId: asText(row.audit_id), jobType: row.job_type, operationScope: row.operation_scope, idempotencyKey: row.idempotency_key, inputFingerprint: row.input_fingerprint, payload: row.payload, evidenceId: asText(row.evidence_id), status: row.status, progress: asCount(row.progress), attemptCount: asCount(row.attempt_count), maxAttempts: asCount(row.max_attempts), lastErrorCode: asText(row.last_error_code), lastErrorMessageSanitized: asText(row.last_error_message_sanitized), availableAt: row.available_at, createdAt: row.created_at, startedAt: asText(row.started_at), finishedAt: asText(row.finished_at), timeoutAt: asText(row.timeout_at) }; }
function toClaim(row: ClaimRow): ClaimedJob { return { jobId: row.job_id, attemptNumber: asCount(row.attempt_number), auditId: asText(row.audit_id), jobType: row.job_type, payload: row.payload, evidenceId: asText(row.evidence_id), attemptCount: asCount(row.attempt_count), maxAttempts: asCount(row.max_attempts), timeoutAt: asText(row.timeout_at) }; }
function toArtifact(row: ArtifactRow): JobArtifactRecord { return { id: row.id, jobId: row.job_id, evidenceId: asText(row.evidence_id), artifactType: row.artifact_type, result: row.result, contentSha256: asText(row.content_sha256), extractorVersion: asText(row.extractor_version), provider: asText(row.provider), createdAt: row.created_at }; }
function firstRpcRow(data: unknown): unknown { return Array.isArray(data) ? (data[0] ?? null) : data; }

export function createJobRepository(database: DatabaseClient) {
  async function rpc(name: string, args: Record<string, unknown>): Promise<unknown> { if (!database.rpc) throw new Error(`La base no soporta RPC ${name}.`); const { data, error } = await database.rpc(name, args); if (error) throw new Error(error.message ?? `Fallo la RPC ${name}.`); return data; }
  return {
    async enqueue(input: EnqueueJobInput): Promise<JobRecord> { return toJob((await rpc('enqueue_job', { p_audit_id: input.auditId, p_job_type: input.jobType, p_operation_scope: input.operationScope, p_idempotency_key: input.idempotencyKey, p_input_fingerprint: input.inputFingerprint, p_payload: input.payload ?? {}, p_evidence_id: input.evidenceId ?? null, p_max_attempts: input.maxAttempts ?? 2, p_actor_id: input.actorId ?? null })) as JobRow); },
    async claimNext(workerId: string, leaseSeconds = 60): Promise<ClaimedJob | null> { const row = firstRpcRow(await rpc('claim_next_job', { p_worker_id: workerId, p_lease_seconds: leaseSeconds })); return row ? toClaim(row as ClaimRow) : null; },
    complete(jobId: string, workerId: string, progress = 100): Promise<unknown> { return rpc('complete_job', { p_job_id: jobId, p_worker_id: workerId, p_progress: progress }); },
    scheduleRetry(jobId: string, workerId: string, errorCode: string, errorMessageSanitized: string, delaySeconds = 30): Promise<unknown> { return rpc('schedule_job_retry', { p_job_id: jobId, p_worker_id: workerId, p_error_code: errorCode, p_error_message_sanitized: errorMessageSanitized, p_delay_seconds: delaySeconds }); },
    failPermanent(jobId: string, workerId: string, errorCode: string, errorMessageSanitized: string): Promise<unknown> { return rpc('fail_job_permanent', { p_job_id: jobId, p_worker_id: workerId, p_error_code: errorCode, p_error_message_sanitized: errorMessageSanitized }); },
    recordArtifact(jobId: string, artifactType: string, result: unknown, opts: { evidenceId?: string | null; contentSha256?: string | null; extractorVersion?: string | null; provider?: string | null } = {}): Promise<unknown> { return rpc('record_job_artifact', { p_job_id: jobId, p_artifact_type: artifactType, p_result: result, p_evidence_id: opts.evidenceId ?? null, p_content_sha256: opts.contentSha256 ?? null, p_extractor_version: opts.extractorVersion ?? null, p_provider: opts.provider ?? null }); },
    async listByAudit(auditId: string): Promise<JobRecord[]> { const { data, error } = await database.from('jobs').select(JOB_COLUMNS).eq('audit_id', auditId).order('created_at', { ascending: false }); if (error) throw new Error(error.message ?? `No se pudieron listar jobs de ${auditId}.`); return ((data ?? []) as JobRow[]).map(toJob); },
    async listArtifactsByAudit(auditId: string): Promise<JobArtifactRecord[]> { const jobs = await this.listByAudit(auditId); if (jobs.length === 0) return []; const { data, error } = await database.from('job_artifacts').select(ARTIFACT_COLUMNS).in('job_id', jobs.map((job) => job.id)).order('created_at', { ascending: false }); if (error) throw new Error(error.message ?? `No se pudieron listar artefactos de ${auditId}.`); return ((data ?? []) as ArtifactRow[]).map(toArtifact); },
    async listArtifacts(): Promise<JobArtifactRecord[]> { const { data, error } = await database.from('job_artifacts').select(ARTIFACT_COLUMNS).order('created_at', { ascending: false }); if (error) throw new Error(error.message ?? 'No se pudieron listar artefactos.'); return ((data ?? []) as ArtifactRow[]).map(toArtifact); },
  };
}

export type JobRepository = ReturnType<typeof createJobRepository>;
